name: Build Unsimplifier Releases

on:
  push:
    paths:
      - '.github/workflows/*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Install npm dependencies
      run: npm install
    
    # - name: Print all tags
    #   run: git tag
    
    # - name: Print latest tag name
    #   run: git for-each-ref --count=1 --sort=-taggerdate --format '%(tag)' refs/tags
    
    - name: Get latest git tag
      id: get_latest_tag
      run: echo "TAG_NAME=$(git tag)" >> $GITHUB_ENV
      
    - name: Build Unsimplifier
      run: PUBLIC_OW_VERSION="$TAG_NAME" PUBLIC_VERSION_TIMESTAMP=$(date +%s)000 PUBLIC_IS_DEV_VERSION=0 PUBLIC_DEBUG=0 npm run build
    
    - name: Embed current version number in build
      run: echo "$TAG_NAME" > build/versionnr.txt
    
    - name: Upload build folder
      uses: actions/upload-artifact@v4
      with:
        name: Unsimplifier-build
        path: build
        
